name: auth3
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.4.0'  # Using latest stable Dart version (as of March 24, 2024)

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: '<2.9.0'  # Consider updating to the latest stable version if compatible
  firebase_auth: '<4.4.0'  # Consider updating to the latest stable version if compatible

  charts_flutter: ^0.12.0  # Consider updating to the latest stable version if compatible
  pedometer: '<4.0.1'      # Consider updating to the latest stable version if compatible
  cloud_firestore: '<4.5.0' # Consider updating to the latest stable version if compatible
  image_picker: '<0.8.7'   # Consider updating to the latest stable version if compatible
  video_player: ^2.2.12
  fl_chart: '<0.60.0'     # Consider updating to the latest stable version if compatible
  url_launcher: ^6.0.9
  google_sign_in: '>=6.1.0 <7.0.0'
  provider: ^6.1.2
  sensors: ^2.0.3
  geolocator: ^11.0.0
  path_provider: ^2.0.2
  mockito: '<5.3.0'        # Consider updating to the latest stable version if compatible

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: '<0.12.0'
  test: '>=1.21.5 <3.4.0'  # Using latest stable Dart version (as of March 24, 2024)

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.png"

flutter_lints: ^2.0.0



flutter:


  uses-material-design: true
  assets:
    - assets/FitFlow_logo.png
    - assets/insta.png
    - assets/fb.png
    - assets/tele.png
    - assets/x.png
    - assets/hfBG.jpg
    - assets/logo.png
    - assets/welcomeBGF.jpg
    - assets/regBG.jpg
    - assets/loginBG.jpg
    - assets/cal3.png
    - assets/db.png
    - assets/feed.png
    - assets/homeBG2.jpg
    - assets/pro2.png
    - assets/set.png
    - assets/inputBG.jpg
    - assets/avatar/avatar1.jpg
    - assets/avatar/avatar2.jpg
    - assets/avatar/avatar3.jpg
    - assets/avatar/avatar4.jpg
    - assets/avatar/avatar5.png
    - assets/avatar/avatar6.jpg
    - assets/profileBG.png
    - assets/splashBGV.mp4
    - assets/welcomeBGF2.png
    - assets/loginBG.png
    - assets/signupBG.png
    - assets/homeBg.png
    - assets/lbgl.png
    - assets/lbgd.png
    - assets/appbarBG.png
    - assets/weightBg.png
    - assets/aboutBg.png
    - assets/usernameBg.png
    - assets/femaleBtn.png
    - assets/maleBtn.png
    - assets/inputBg.png
    - assets/begBtn.png
    - assets/proBtn.png
    - assets/midBtn.png
    - assets/avatar/avatar6.png
    - assets/avatar/avatar7.jpg
    - assets/avatar/avatar8.png
    - assets/avatar/avatar9.jpg
    - assets/avatar/avatar10.jpg
    - assets/avatar/avatar11.jpg
    - assets/avatar/avatar12.jpg
    - assets/avatar/avatar13.jpg
    - assets/avatar/avatar14.jpg
    - assets/avatar/avatar15.jpg
    - assets/avatar/avatar16.jpg
    - assets/avatar/avatar17.jpg
    - assets/avatar/avatar18.jpg
    - assets/avatar/avatar19.jpg
    - assets/avatar/avatar20.jpg
    - assets/stepBg.jpg
    - assets/bmrBg.jpg
    - assets/bmrtdeeBg.jpg
    - assets/workoutShowBg.jpg
    - assets/aboutBg.jpg
    - assets/aboutBg2.png